projects:
  default:
    schema:
      - http://localhost:4000/graphql
    documents: "./packages/cli/src/lib/api/**/*.graphql"
    extensions:
      codegen:
        generates:
          ./packages/cli/src/lib/api/schema.json:
            plugins:
              - introspection
            config:
              minify: true
          ./packages/types/api.ts:
            plugins:
              - typescript
              - typescript-operations
          ./packages/cli/src/lib/api/sdk.ts:
            plugins:
              - typescript
              - typescript-operations
              - typescript-graphql-request
            config:
              useTypeImports: true
