projects:
  default:
    schema:
      - http://localhost:4000/graphql
    documents: "src/lib/api/**/*.graphql"
    extensions:
      codegen:
        generates:
          src/lib/api/schema.json:
            plugins:
              - introspection
            config:
              minify: true
          src/lib/api/sdk.ts:
            plugins:
              - typescript
              - typescript-operations
              - typescript-graphql-request
            config:
              useTypeImports: true
