name: Semantic Release

on:
  push:
    branches:
      - beta
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Install semantic-release
        run: yarn global add semantic-release semantic-release-monorepo @semantic-release/changelog @semantic-release/npm

      - name: Release
        run: yarn workspaces run semantic-release -e semantic-release-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
